name: Publish to Tencent COS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency: 
      group: 'xuegao-blog'
      cancel-in-progress: true

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo -v --minify

      # 发布到腾讯云COS中，使用全球加速
      # 由于万恶的腾讯云的cli工具设计缺陷，导致全球加速时无法进行同步删除
      # 为了解决这个问题，不得不先全球加速同步推送，再使用地域同步以删除不需要的文件
      # 推送文件需要保证速度，同步删除则不急，因此允许网络不稳定的情况下等待下一次Action触发再尝试删除
      
      # 使用全球加速同步推送一次
      # 这个阶段同步删除时会报错，但是不影响继续执行
      - name: Upload to Accelerate COS
        uses: XUEGAONET/tencent-cos-action@v0.2.0
        with:
          args: upload -rsf --delete ./public/ /
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}

      # 使用地域，再次同步推送一次。此时由于MD5验证都通过，因此只会删除本地已经不存在了的文件
      - name: Sync Deleting
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -rsf --delete ./public/ /
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
          region: ap-guangzhou
